name: rojnivis
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  
  # DI
  get_it: ^8.0.3
  injectable: ^2.5.0
  
  # Navigation
  go_router: ^14.6.2
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2 # Added for Settings
  
  # Localization & Date
  easy_localization: ^3.0.7
  intl: ^0.19.0
  table_calendar: ^3.1.2
  
  # Media & Files
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  record: ^6.2.0
  # record_linux: ^1.3.0 # Removed manual dependency, let record handle it
  audioplayers: ^6.0.0
  open_filex: ^4.5.0
  path_provider: ^2.1.5
  
  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.2

  
  # UI/UX & Utils
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  uuid: ^4.5.1
  
  # Security & AI
  local_auth: ^2.3.0
  crypto: ^3.0.6
  google_generative_ai: ^0.4.5

  unified_flutter_features:
    path: /home/garuda/Masa端st端/unified_flutter_features
  
  remote_auth_module:
    path: /home/garuda/Masa端st端/remote_auth_module/
  firebase_remote_config: ^6.1.4
  

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.14
  injectable_generator: ^2.6.2
  hive_generator: ^2.0.1
  flutter_native_splash: ^2.4.0

  # Testing
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/
    - assets/stickers/
    - assets/sounds/

flutter_native_splash:
  color: "#151922"
  image: android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android_12:
    color: "#151922"
    image: android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
