name: rojnivis
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.7
  
  # DI
  get_it: ^8.0.3
  injectable: ^2.5.0
  
  # Navigation
  go_router: ^14.6.2
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2 # Added for Settings
  
  # Localization & Date
  easy_localization: ^3.0.7
  intl: ^0.19.0
  table_calendar: ^3.1.2
  
  # Media & Files
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  record: ^6.2.0
  # record_linux: ^1.3.0 # Removed manual dependency, let record handle it
  audioplayers: ^6.0.0
  open_filex: ^4.5.0
  path_provider: ^2.1.5
  
  # UI/UX & Utils
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  uuid: ^4.5.1
  
  # Security (New)
  local_auth: ^2.3.0
  crypto: ^3.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.14
  injectable_generator: ^2.6.2
  hive_generator: ^2.0.1
  
  # Testing
  mocktail: ^1.0.4
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
  
  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/
    - assets/sounds/
